### ISSUE TITLE
command-line utility to export data, run segmentation training, and update model with eScriptorium API and slurm

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/htr2hpc#24]
- [x] use eScriptorium API for getting doc & parts as xml
   - [x] download model, create new model
- [x] write methods to download training data
   - [x] correct region block data in output
- [x] run kraken through command line (or python API if easier)
- [x] #29
- [x] #30
- [x] review part apis and kraken arrow - can we convert directly without going to alto + image

assuming local install for now (running on the cluster) and conda env setup not automated (yet)

**Comment by cmroughan** [comment]
Ran tests to confirm different types of functional behavior, and all ran successfully. The tests were the following:

- run training on a complete document, training the model "from scratch" (on blla.mlmodel)
- run training on a complete document, refining a model
- run training on a partial document (contiguous parts), training the model "from scratch"
- run training on a partial document (non-contiguous parts), refining a model

Behavior for all four was as expected. A record of the commands and debug output is below:

---

`htr2hpc-train segmentation https://test-htr.lib.princeton.edu/ segtrain_doc30-refine --document 30 --model 3`

```
DEBUG:htr2hpc.train.apps:sbatch file
: #!/bin/sh

#SBATCH --cpus-per-task       8
#SBATCH --gres                gpu:1
#SBATCH --job-name            segtrain
#SBATCH --mem-per-cpu         4G
#SBATCH --nodes               1
#SBATCH --ntasks              1
#SBATCH --output              segtrain_%A.out
#SBATCH --time                0-00:20:00

module purge
module load anaconda3/2024.6
conda activate htr2hpc

DEBUG:htr2hpc.train.apps:segtrain command: ketos segtrain --epochs 200 --resize new -i /scratch/gpfs/croughan/segtrain_doc30-refine/bnseg_complex.mlmodel -o /scratch/gpfs/croughan/segtrain_doc30-refine/output_model/model --workers 8 -d cuda:0 -f xml /scratch/gpfs/croughan/segtrain_doc30-refine/parts/*.xml 
Submitted batch job 60580418

Slurm job 60580418 | total time: 07:29, status: COMPLETING  ~ run time: 07:19 
Job 60580418 is no longer queued; ending status: COMPLETED
Job output should be in segtrain_doc30-refine/segtrain_60580418.out
```

---

`htr2hpc-train segmentation https://test-htr.lib.princeton.edu/ segtrain_doc30-scratch --document 30`

```
DEBUG:htr2hpc.train.apps:sbatch file
: #!/bin/sh

#SBATCH --cpus-per-task       8
#SBATCH --gres                gpu:1
#SBATCH --job-name            segtrain
#SBATCH --mem-per-cpu         4G
#SBATCH --nodes               1
#SBATCH --ntasks              1
#SBATCH --output              segtrain_%A.out
#SBATCH --time                0-00:20:00

module purge
module load anaconda3/2024.6
conda activate htr2hpc

DEBUG:htr2hpc.train.apps:segtrain command: ketos segtrain --epochs 200 --resize new -i /home/croughan/.conda/envs/htr2hpc/lib/python3.11/site-packages/kraken/blla.mlmodel -o /scratch/gpfs/croughan/segtrain_doc30-scratch/output_model/model --workers 8 -d cuda:0 -f xml /scratch/gpfs/croughan/segtrain_doc30-scratch/parts/*.xml 
Submitted batch job 60580431

Slurm job 60580431 | total time: 07:22, status: COMPLETING  ~ run time: 06:59 
Job 60580431 is no longer queued; ending status: COMPLETED
Job output should be in segtrain_doc30-scratch/segtrain_60580431.out
```

---

`htr2hpc-train segmentation https://test-htr.lib.princeton.edu/ segtrain_doc27-parts-refine --document 27 --model 3 --parts 54377-54406`

```
DEBUG:htr2hpc.train.apps:sbatch file
: #!/bin/sh

#SBATCH --cpus-per-task       8
#SBATCH --gres                gpu:1
#SBATCH --job-name            segtrain
#SBATCH --mem-per-cpu         4G
#SBATCH --nodes               1
#SBATCH --ntasks              1
#SBATCH --output              segtrain_%A.out
#SBATCH --time                0-00:20:00

module purge
module load anaconda3/2024.6
conda activate htr2hpc

DEBUG:htr2hpc.train.apps:segtrain command: ketos segtrain --epochs 200 --resize new -i /scratch/gpfs/croughan/segtrain_doc27-parts-refine/bnseg_complex.mlmodel -o /scratch/gpfs/croughan/segtrain_doc27-parts-refine/output_model/model --workers 8 -d cuda:0 -f xml /scratch/gpfs/croughan/segtrain_doc27-parts-refine/parts/*.xml 
Submitted batch job 60580437

Slurm job 60580437 | total time: 18:37, status: COMPLETING  ~ run time: 18:11 
Job 60580437 is no longer queued; ending status: COMPLETED
Job output should be in segtrain_doc27-parts-refine/segtrain_60580437.out
```

---

`htr2hpc-train segmentation https://test-htr.lib.princeton.edu/ segtrain_doc27-parts-scratch --document 27 --parts 54377,54378,54379,54380,54381,54382,54383,54384,54385,54386,54390,54391,54392,54393,54394,54395,54396,54397,54398,54399`

```
DEBUG:htr2hpc.train.apps:sbatch file
: #!/bin/sh

#SBATCH --cpus-per-task       8
#SBATCH --gres                gpu:1
#SBATCH --job-name            segtrain
#SBATCH --mem-per-cpu         4G
#SBATCH --nodes               1
#SBATCH --ntasks              1
#SBATCH --output              segtrain_%A.out
#SBATCH --time                0-00:20:00

module purge
module load anaconda3/2024.6
conda activate htr2hpc

DEBUG:htr2hpc.train.apps:segtrain command: ketos segtrain --epochs 200 --resize new -i /home/croughan/.conda/envs/htr2hpc/lib/python3.11/site-packages/kraken/blla.mlmodel -o /scratch/gpfs/croughan/segtrain_doc27-parts-scratch/output_model/model --workers 8 -d cuda:0 -f xml /scratch/gpfs/croughan/segtrain_doc27-parts-scratch/parts/*.xml 
Submitted batch job 60581296

Slurm job 60581296 | total time: 12:50, status: COMPLETING  ~ run time: 12:47 
Job 60581296 is no longer queued; ending status: COMPLETED
Job output should be in segtrain_doc27-parts-scratch/segtrain_60581296.out
```

**Comment by cmroughan** [comment]
Additionally ran some tests just to see how things currently break when PKs that do not exist (or that the user does not have access to) are passed to the script. Realistically, in the complete version of this functionality there will be guardrails against that, since users should only have the ability to select what they have access to in the GUI anyway.

Broke things by inputting parts that did not exist, a model that did not exist, and a doc that did not exist.

---

`htr2hpc-train segmentation https://test-htr.lib.princeton.edu/ segtrain_doc27-wrong-parts --document 27 --model 3 --parts 54436-54440`

```
DEBUG:htr2hpc.api_client:get https://test-htr.lib.princeton.edu/api/documents/27/parts/54437/ 404: 0.130117 sec
ERROR:htr2hpc.api_client:Error: not found
...
AttributeError: 'NoneType' object has no attribute 'json'
```

---

`htr2hpc-train segmentation https://test-htr.lib.princeton.edu/ segtrain_doc30-wrong-model --document 30 --model 130`

```
DEBUG:htr2hpc.api_client:get https://test-htr.lib.princeton.edu/api/models/130/ 404: 0.058728 sec
ERROR:htr2hpc.api_client:Error: not found
...
AttributeError: 'NoneType' object has no attribute 'json'
```

---

`htr2hpc-train segmentation https://test-htr.lib.princeton.edu/ segtrain_doc40-wrong-doc --document 40`

```
DEBUG:htr2hpc.api_client:get https://test-htr.lib.princeton.edu/api/documents/40/parts/ 200: 0.139846 sec
...
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
...
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by cmroughan** [comment]
For tackling #29, as mentioned for segtraining the regular behavior for eScriptorium seems to be to present the user with all models created during training (as opposed to transcription training, which selects only the `_best` model). eScriptorium's code uses kraken's default `SEGMENTATION_HYPER_PARAMS` where the number of epochs is set as 50.

So we can remove the ` --epochs 200` from our kraken command and just let it use its default 50 epochs, and then we will want to use the API to POST those 50 new models back into the eScriptorium instance.

This is where the fact that the accuracy is read only in the API will be a pain, because for now we will just end up with 50 models available in the GUI with no guidance whatsoever as to which might be better than the others. So eventually we will want to address that (is it possible for us to overwrite that with the present htr2hpc repo?) but for now step 1 is just getting those 50 models successfully imported.

**Comment by rlskoeser** [comment]
> This is where the fact that the accuracy is read only in the API will be a pain, because for now we will just end up with 50 models available in the GUI with no guidance whatsoever as to which might be better than the others. So eventually we will want to address that (is it possible for us to overwrite that with the present htr2hpc repo?) but for now step 1 is just getting those 50 models successfully imported.

Good thought! One option is to add a signal handler that can attach to model creation and set accuracy if it is not set. Before we do that I'd like to poke around a little in the eScriptorium code and see where/when it is set normally.

**Comment by rlskoeser** [comment]
now complete including the split out subtasks / sub issues
