### ISSUE TITLE
create or update model in eScriptorium via API after segmentation training completes

### ISSUE THREAD

**Issue by mnaydan** [Princeton-CDH/htr2hpc#29]

**Comment by cmroughan** [comment]
Moving this comment in #24 to this subissue, as it is more directly relevant here:

> As mentioned for segtraining the regular behavior for eScriptorium seems to be to present the user with all models created during training (as opposed to transcription training, which selects only the `_best` model). eScriptorium's code uses kraken's default `SEGMENTATION_HYPER_PARAMS` where the number of epochs is set as 50.
>
> So we can remove the  `--epochs 200` from our kraken command and just let it use its default 50 epochs, and then we will want to use the API to POST those 50 new models back into the eScriptorium instance.
> 
> This is where the fact that the accuracy is read only in the API will be a pain, because for now we will just end up with 50 models available in the GUI with no guidance whatsoever as to which might be better than the others. So eventually we will want to address that (is it possible for us to overwrite that with the present htr2hpc repo?) but for now step 1 is just getting those 50 models successfully imported.

**Comment by rlskoeser** [comment]
completed in #31
